### PR TITLE
Stop ignoring glowing chests (beta).

### PR DESCRIPTION
**Pull request by mishander**
I just tried all 3 AI addons and yours is by far the best one. It allows me to play tome again =)
I noticed that its ignoring chest and just wrote a quickfix, which seems to be working so far. 
Never wrote in lua before, so proly code isnt ideal, but well, it works xD

### CODE REVIEW

**Comment by SkoobyDoo** [comment]
I like the fix but I'm not certain taking the action at this point in the act() function is appropriate.

It might be worth moving it down towards 
https://github.com/SkoobyDoo/tome4-SkooBot/blob/281804a9cc602b88a712880056d6154757d04793/superload/mod/class/Player.lua#L645-L656

 and checking if `not _M.skoobot.tempvals.state = SAI_STATE_FIGHT`

Alternatively, it might be worth creating an entire state string and handling code for investigating terrain, this might be useful in other cases as well for other things that don't get handled properly by the default explore AI.

My concern is that the code as written might miss checks for dangerous debuffs or other states that should have a higher priority than opening a chest--this could lead to reckless RIP.

**Comment by mishander** [comment]
well, SAI_STATE_FIGHT is right now set only when there are hostiles in sight, and I added that when we don't have hostiles in sight. I I agree it should be done later after everything else since its not a priority.

**Comment by mishander** [comment]
Well, I looked at it a bit more and I don't like that check for air is when we resting - during the fight it could be you don't have air as well? I think this whole priority of checks system need to be a little bit changed, so maybe you would accept this as-is now?

**Comment by mishander** [comment]
So I didn't have time to split this nicely into commits, but I added/fixed a bunch of stuff:
- mainly not working path to air is actually working now.
- checking simply power level leads to a stop every time you see bunch of common mobs, and if you increase threshold - you start getting into hard situations where couple of rare mobs are threatening to kill you. I added some coefficient to apply to power level since its clearly not working as is. 
- trying to mimic auto-explore : I hated I need to use autoexprore to go back and forth after clearing level and that I cannot start this on level entrance, so I fixed it and rebinded my autoexprore hotkey to starting this one and now it works great.
- fixed this annoying freeze bug where game stops for a full minute when someone PIN (or DOMINATE) you.
- added bat file to zip, copy addon and run game
- added IGNORE_DAMAGE_HEALTH_RATIO setting - where we ignore all shit like pins or DOT damage if we say have more than say 90% of HP. Removed most of unneeded stops entirely.
- Added HP to calculation of our powerlevel - hero with 55% of HP is not as powerful as with 100%. Ofc it should be more sophisticated but so far I like it.
- Added bunch of debug output which may need or need not be wrapped in some OUTPUT_IF_DEBUG macro function

PS. I only have some time at night to do it when I play, and I really wanted to split that nicely into CLs but simply didn't had time.

PSS. In some rare cases we are not picking up stuff from glowing chests now (because sometimes auto-explore is not doing that). I even created a forum account to ask about that but nobody bothered to answer me.
http://forums.te4.org/viewtopic.php?f=42&t=51925

**Comment by mishander** [comment]
oh, btw if you leave your email or telegram or something here it would be great.

**Comment by mishander** [comment]
reworking some things.

**Pull request closed without merging**
