### PR TITLE
Fix soft-locks on SAI_STATE_EXPLORE. Resovles #46

### PR DESCRIPTION
**Pull request by yura9111**
somewhat of a dirty hack, but have no idea how to make a proper one and the bug is CRITICAL.

### CODE REVIEW

**Comment by SkoobyDoo** [comment]
I'll pull up the code and review this some time this weekend....I swear there is already a similar loop counter in the code but I might be mis-remembering or remembering something I cut out at some point.

If I can't immediately come up with a better solution I'll merge and release this, as you're right that it's a very critical issue.

**Comment by SkoobyDoo** [comment]
So looking into it it seems that I have already written a different solution after I looked into this issue the first time, which was never released. the game.player:autoExplore() function can return false which indicates that for some reason the function cannot be called. (See https://github.com/SkoobyDoo/tome4-SkooBot/commit/0d0e4e2cf70dbe0ca07515dd2e1d5a18ef712b32 )

Yeesh, looking further my last commit was actually incrementing version number and prepping for release....not sure why I wouldn't have actually done the final step of releasing it...

That said, I just spent the last 2 hours trying to get the addon developer menu to pop up in the debug menu and I've been unable to do so... I should be able to troubleshoot that before the end of tomorrow.

**Comment by yura9111** [comment]
Current version 0.10 already checks for autoExplore() to return true, but still gets soft locked.

**Comment by SkoobyDoo** [comment]
Unless I screwed up my commits (possible), this should be novel code, unless you're saying you took this modification, added it to your build, and reproduced the freeze.

Here's a reference to the 0.10 version of Player.lua: https://github.com/SkoobyDoo/tome4-SkooBot/blob/210396163cb68229717f4e96af550b16abbf784a/superload/mod/class/Player.lua#L224

**Comment by yura9111** [comment]
true my bad

**Comment by SkoobyDoo** [comment]
Closing PR as the issue was resolved by b9ec448e79fba191fe05b298ff422f09e6d4f59f

**Pull request closed without merging**
